baseurl = "https://www.flaky.io/"
languageCode = "en-us"
title = "brkcmd"
theme = "tanaka"
uglyurls = true

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[outputs]
    home = [ "HTML", "Atom" ]
    section = [ "HTML", "Atom" ]
    taxonomy = [ "HTML", "Atom" ]

[mediaTypes]
    [mediaTypes."application/atom"]
        suffix = "atom.xml"

[outputFormats]
    [outputFormats.Atom]
        mediaType = "application/atom"
        baseName = "index"
        isPlainText = false

[params]
    feedlimit = 20
    [params.collectivephrases]
        tag = "tagged as"
        category = "categorized as"
        series = "in the series"
