baseurl = "https://www.brkcmd.com/"
disableKinds = ["taxonomyTerm", "section"]
enableemoji = false
languageCode = "en-us"
newContentEditor = "sensible-editor"
paginate = 10
paginatePath = "page"
publishDir = "public"
preserveTaxonomyNames = true
pygmentsStyle = "monokai"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = false
pygmentsUseClasses = true
pygmentsOptions = ""
theme = "tanaka"
title = "brkcmd"
uglyurls = true

[blackfriday]
    smartypants = false

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[outputs]
    home = [ "HTML", "Atom" ]
    section = [ "HTML", "Atom" ]
    taxonomy = [ "HTML", "Atom" ]
    taxonomyTerm = [ "HTML", "Atom" ]

[params]
    feedlimit = 20
    contactemail = "editor@brkcmd.com"
    contactsubject = "Interesting, but did you consider this?"
    [params.license]
        name = "CC-BY-SA 4.0"
        url = "https://creativecommons.org/licenses/by-sa/4.0/"
